DO $$
BEGIN
   IF NOT EXISTS (
      SELECT 1 FROM pg_roles WHERE rolname = 'az'
   ) THEN
      CREATE ROLE az WITH LOGIN PASSWORD 'azaz';
   END IF;
END
$$;
CREATE SCHEMA IF NOT EXISTS az AUTHORIZATION az;

GRANT ALL ON SCHEMA az TO az;
GRANT ALL ON ALL TABLES IN SCHEMA az TO az;
GRANT ALL ON ALL SEQUENCES IN SCHEMA az TO az;
ALTER DEFAULT PRIVILEGES IN SCHEMA az GRANT ALL ON TABLES TO az;
ALTER DEFAULT PRIVILEGES IN SCHEMA az GRANT ALL ON SEQUENCES TO az;

DROP TABLE IF EXISTS az.t_busyo CASCADE;
CREATE TABLE az.t_busyo (
    id bigint NOT NULL,
    busyo_cd character varying(10) NOT NULL,
    busyo_name character varying(100) NOT NULL
);
ALTER TABLE az.t_busyo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME az.seq_busyo_id START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);
ALTER TABLE ONLY az.t_busyo
    ADD CONSTRAINT pk_t_busyo PRIMARY KEY (id);

DROP TABLE IF EXISTS az.t_syain CASCADE;
CREATE TABLE az.t_syain (
    id bigint NOT NULL,
    syain_cd character varying(10) NOT NULL,
    syain_name character varying(100) NOT NULL
);
ALTER TABLE az.t_syain ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME az.seq_syain_id START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);
ALTER TABLE ONLY az.t_syain
    ADD CONSTRAINT pk_t_syain PRIMARY KEY (id);

DROP TABLE IF EXISTS az.t_syozoku CASCADE;
CREATE TABLE az.t_syozoku (
    id bigint NOT NULL,
    syain_id bigint NOT NULL,
    busyo_id bigint NOT NULL,
    start_date date NOT NULL
);
ALTER TABLE az.t_syozoku ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME az.seq_syozoku_id START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);
ALTER TABLE ONLY az.t_syozoku
    ADD CONSTRAINT pk_t_syozoku PRIMARY KEY (id);

INSERT INTO az.t_busyo (id, busyo_cd, busyo_name) VALUES
(10001, 'B001', '部署１'),
(10002, 'B002', '部署２');
INSERT INTO az.t_syain (id, syain_cd, syain_name) VALUES
(10001, 'S001', '社員１'),
(10002, 'S002', '社員２'),
(10003, 'S003', '社員３'),
(10004, 'S004', '社員４');
INSERT INTO az.t_syozoku (id, syain_id, busyo_id, start_date) VALUES
(20001, 10001, 10001, '2025-01-01'),
(20002, 10002, 10002, '2025-01-02'),
(20003, 10003, 10001, '2025-01-03'),
(20004, 10004, 10002, '2025-01-04');